import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const out='ai_docs/reports/x3-u4-evidence',read=f=>JSON.parse(fs.readFileSync(`${out}/${f}`,'utf8'));
const sha=x=>createHash('sha256').update(x).digest('hex'),git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
assert.equal(git('rev-parse','HEAD'),'801314dc51a5376e68f812d60331bdc597e7625f');assert.equal(git('diff','--cached','--name-only'),'');
const protectedFiles=['src/engine/UI/DetailGenerator.ts','src/engine/UI/ItemKnowledge.ts','src/components/InventoryOverlay.vue','src/engine/Items/ItemLoader.ts'];
const protectedRows=protectedFiles.map(f=>{const current=fs.readFileSync(f),head=execFileSync('git',['show',`HEAD:brogue-web/${f}`]);assert.deepEqual(current,head);return{file:f,sha256:sha(current),sameAsHEAD:true}});
const scope=fs.readFileSync(`${out}/targeted-scope.txt`,'utf8').trim().split('\n');
const refs=execFileSync('rg',['-l','stepAutoPath|autoPath|isAutoExploring|visibleMonsters|visibleItems|everSeen|logger|escape','src','scripts','-g','*.test.ts','-g','*.spec.ts'],{encoding:'utf8'}).trim().split('\n');assert.deepEqual(refs.filter(f=>!scope.includes(f)),[]);
const initial=read('targeted-results.json'),final=read('followup-results.json');
const outcomes=new Map(initial.testResults.map(f=>[path.relative(process.cwd(),f.name),f]));for(const f of final.testResults)outcomes.set(path.relative(process.cwd(),f.name),f);
assert.deepEqual(scope.filter(f=>!outcomes.has(f)),[]);
const unresolved=[...outcomes].flatMap(([file,f])=>f.assertionResults.filter(t=>t.status==='failed').map(t=>({file,test:t.fullName})));assert.deepEqual(unresolved,[]);
const counts={};for(const f of outcomes.values())for(const t of f.assertionResults)counts[t.status]=(counts[t.status]??0)+1;
assert(read('final-validation.json').every(r=>r.code===0));assert.equal(read('targeted-validation.json').changed.length,0);assert.equal(read('final-input-check.json').changed.length,0);
const inputs=read('final-inputs.json');assert.deepEqual(Object.keys(inputs).filter(f=>sha(fs.readFileSync(f))!==inputs[f]),[]);
const golden=read('golden-registration.json');assert.equal(sha(fs.readFileSync('ai_docs/reports/u-r4-trace.json.gz')),golden.after);
for(const f of ['ai_docs/reports/u-r2-trace.json','ai_docs/reports/u-r3-trace.json.gz','package-lock.json'])assert.deepEqual(fs.readFileSync(f),execFileSync('git',['show',`HEAD:brogue-web/${f}`]));
const changed=git('ls-files','-m','-o','--exclude-standard').split('\n').filter(Boolean);
const crlf=changed.filter(f=>fs.existsSync(f)&&!f.endsWith('.gz')&&fs.readFileSync(f).includes(Buffer.from('\r\n')));assert.deepEqual(crlf,[]);
const png=fs.readdirSync(out).filter(f=>f.endsWith('.png')).map(f=>`${out}/${f}`);for(const f of png)assert.equal(git('check-ignore',f),f);assert.equal(git('ls-files','--',`${out}/*.png`),'');git('diff','--check');
const addedRng=git('diff','--','src/engine','src/entities').split('\n').filter(l=>l.startsWith('+')&&!l.startsWith('+++')&&/\brng\.(rand|shuffle|seed|setRNG|next)/.test(l));assert.deepEqual(addedRng,[]);
const browser=read('browser.json');assert.equal(browser.results.length,8);assert.deepEqual(browser.errors,[]);
fs.writeFileSync(`${out}/final-check.json`,JSON.stringify({head:git('rev-parse','HEAD'),scopeFiles:scope.length,referenceFiles:refs.length,mergedFiles:outcomes.size,mergedTests:counts,finalFrozenInputs:Object.keys(inputs).length,protected:protectedRows,crlf,pngIgnored:png.length,staged:false,newRngCalls:addedRng,browserScenarios:browser.results.length},null,2)+'\n');
console.log('Final checks passed:',{scope:scope.length,mergedFiles:outcomes.size,counts,frozen:Object.keys(inputs).length,pngIgnored:png.length});
